
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  rate-limiter:
    image: ratelimiter:latest
    ports:
      - "8080:8080"
    env_file:
      - .env_lado

volumes:
  redis-data: